spring.application.name=helpdesk

# PostgreSQL Configuration Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk_db
spring.datasource.username=postgres
spring.datasource.password=123

#user & password
#spring.security.user.name=user
#spring.security.user.password=1234

# Hibernates Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
